branches:
  only:
    - master
language: php
php:
  - 5.3
before_script:
  - composer update --no-dev
script:
  # Lint check PHP files.
  - find . ! -path "*/vendor/*" \( -type f -name \*.inc -o -name \*.php \) -print0 | xargs -0 -n 1 -P 4 php -l
  # Make sure Switchboard executes cleanly. Should do nothing.
  - php ./switchboard.drush.inc
