<?php
// This file generated by Propel 1.7.1 convert-conf target
// from XML runtime conf file /Users/jpeck/Projects/switchboard/propel/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'brain' => 
    array (
      'adapter' => 'sqlite',
      'connection' => 
      array (
        'dsn' => 'sqlite:./brain/switchboard.sqlite',
      ),
    ),
    'default' => 'brain',
  ),
  'generator_version' => '1.7.1',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-brain-conf.php');
return $conf;