<?php
// This file generated by Propel 1.7.1 convert-conf target
return array (
  'Fluxsauce\\Brain\\Environment' => 'brain/Environment.php',
  'Fluxsauce\\Brain\\EnvironmentPeer' => 'brain/EnvironmentPeer.php',
  'Fluxsauce\\Brain\\EnvironmentQuery' => 'brain/EnvironmentQuery.php',
  'Fluxsauce\\Brain\\map\\EnvironmentTableMap' => 'brain/map/EnvironmentTableMap.php',
  'Fluxsauce\\Brain\\om\\BaseEnvironment' => 'brain/om/BaseEnvironment.php',
  'Fluxsauce\\Brain\\om\\BaseEnvironmentPeer' => 'brain/om/BaseEnvironmentPeer.php',
  'Fluxsauce\\Brain\\om\\BaseEnvironmentQuery' => 'brain/om/BaseEnvironmentQuery.php',
);